nginx:
  image: richarvey/nginx-php-fpm:latest
  restart: always
  ports: 
    - 80:80
  volumes: 
    - .:/var/www/html/
  environment:
    WEBROOT: /var/www/html/lib
    PGID: 1000
    PUID: 1000
    APPLICATION_ENV: development